### ISSUE TITLE
Provide meaningful error message for unset Environment Variables

### ISSUE THREAD

**Issue by robscott** [reactiveops/reckoner#33]
Current sample debug logging shows that the only items that log by default are not very helpful (`Helm upgrade failed. Rolling back datadog`). 
```
reckoner --log-level=DEBUG plot --dry-run --debug --heading datadog course.yml
2019-01-07 12:37:15 robs-mbp.lan root[29719] WARNING The --debug flag will be deprecated.  Please use --helm-args or --dry-run instead.
2019-01-07 12:37:15 robs-mbp.lan root[29719] DEBUG helm help
2019-01-07 12:37:15 robs-mbp.lan root[29719] DEBUG helm version --short --server
2019-01-07 12:37:16 robs-mbp.lan root[29719] DEBUG Installing repository: {'url': 'https://kubernetes-charts-incubator.storage.googleapis.com', 'name': 'incubator'}
2019-01-07 12:37:16 robs-mbp.lan root[29719] DEBUG helm repo list
2019-01-07 12:37:16 robs-mbp.lan root[29719] DEBUG Chart repository incubator already installed
2019-01-07 12:37:16 robs-mbp.lan root[29719] DEBUG Installing repository: {'url': 'https://kubernetes-charts.storage.googleapis.com', 'name': 'stable'}
2019-01-07 12:37:16 robs-mbp.lan root[29719] DEBUG helm repo list
2019-01-07 12:37:17 robs-mbp.lan root[29719] DEBUG Chart repository stable already installed
2019-01-07 12:37:17 robs-mbp.lan root[29719] DEBUG Installing repository: {'url': 'https://charts.gitlab.io', 'name': 'gitlab'}
2019-01-07 12:37:17 robs-mbp.lan root[29719] DEBUG helm repo list
2019-01-07 12:37:17 robs-mbp.lan root[29719] DEBUG Chart repository gitlab already installed
2019-01-07 12:37:17 robs-mbp.lan root[29719] DEBUG helm repo update
2019-01-07 12:37:18 robs-mbp.lan root[29719] INFO Installing datadog
2019-01-07 12:37:18 robs-mbp.lan root[29719] DEBUG helm repo list
2019-01-07 12:37:18 robs-mbp.lan root[29719] DEBUG Chart repository stable already installed
2019-01-07 12:37:18 robs-mbp.lan root[29719] ERROR Helm upgrade failed. Rolling back datadog
2019-01-07 12:37:18 robs-mbp.lan root[29719] DEBUG Traceback (most recent call last):
  File "/Users/rob/.pentagon/venv/lib/python2.7/site-packages/reckoner/course.py", line 118, in plot
    chart.install(namespace=self.namespace, context=self.context)
  File "/Users/rob/.pentagon/venv/lib/python2.7/site-packages/reckoner/chart.py", line 226, in install
    self.__check_env_vars()
  File "/Users/rob/.pentagon/venv/lib/python2.7/site-packages/reckoner/chart.py", line 109, in __check_env_vars
    raise Exception("Missing requirement environment variable: {}".format(e.args[0]))
Exception: Missing requirement environment variable: RABBIT_DEV_PASS
```

**Comment by sudermanjr** [comment]
That's interesting.  I thought the latest version was supposed to address that.  Even more interesting that the error is in the stacktrace ;-)
