### ISSUE TITLE
Something broken in external repo handling

### ISSUE THREAD

**Issue by sudermanjr** [reactiveops/reckoner#42]
when adding an external chart repo, install fails on downloading the chart.  This works outside of reckoner with these commands:

```
helm repo add influx http://influx-charts.storage.googleapis.com
helm install influx/telegraf-ds
```

Here's the debug output:
```
[ do-sfo2-sudermanjr   ] [pw]
 130 ✘ reckoner --log-level=DEBUG plot course.yaml --heading data
2019-01-08 08:40:53 root[36803]    DEBUG helm help
2019-01-08 08:40:53 root[36803]    DEBUG helm version --short --server
2019-01-08 08:40:54 root[36803]    DEBUG Installing repository: {'url': 'https://kubernetes-charts-incubator.storage.googleapis.com', 'name': 'incubator'}
2019-01-08 08:40:54 root[36803]    DEBUG helm repo list
2019-01-08 08:40:54 root[36803]    DEBUG Chart repository incubator already installed
2019-01-08 08:40:54 root[36803]    DEBUG Installing repository: {'url': 'https://kubernetes-charts.storage.googleapis.com', 'name': 'stable'}
2019-01-08 08:40:54 root[36803]    DEBUG helm repo list
2019-01-08 08:40:54 root[36803]    DEBUG Chart repository stable already installed
2019-01-08 08:40:54 root[36803]    DEBUG Installing repository: {'url': 'http://influx-charts.storage.googleapis.com', 'name': 'influx'}
2019-01-08 08:40:54 root[36803]    DEBUG helm repo list
2019-01-08 08:40:54 root[36803]    DEBUG Chart repository influx already installed
2019-01-08 08:40:54 root[36803]    DEBUG helm repo update
2019-01-08 08:40:56 root[36803]    DEBUG Helm Minimum Version is: 2.12.1
2019-01-08 08:40:56 root[36803]    DEBUG helm version --short --client
2019-01-08 08:40:56 root[36803]    DEBUG Helm Installed Version is 2.12.1
2019-01-08 08:40:56 root[36803]    DEBUG Reckoner Minimum Version is 0.10.1
2019-01-08 08:40:56 root[36803]    DEBUG Reckoner Installed Version is 0.10.3
2019-01-08 08:40:56 root[36803]    DEBUG helm version --short --client
2019-01-08 08:40:56 root[36803]     INFO Installing data
2019-01-08 08:40:56 root[36803]    DEBUG helm repo list
2019-01-08 08:40:56 root[36803]    DEBUG Chart repository influx already installed
2019-01-08 08:40:56 root[36803]    DEBUG Updating chart dependencies: influx/influxdb
2019-01-08 08:40:56 root[36803]    DEBUG helm upgrade --install data influx/influxdb --namespace=tick --version=1.7.1
2019-01-08 08:40:57 root[36803]    ERROR Command Failed with output below:
STDOUT:
STDERR: Error: failed to download "influx/influxdb" (hint: running `helm repo update` may help)

COMMAND: helm upgrade --install data influx/influxdb --namespace=tick --version=1.7.1
2019-01-08 08:40:57 root[36803]    ERROR Helm upgrade failed. Rolling back data
2019-01-08 08:40:57 root[36803]    DEBUG Traceback (most recent call last):
  File "/Users/asuderma/repos/reactiveops/reckoner/reckoner/course.py", line 122, in plot
    chart.install(namespace=self.namespace, context=self.context)
  File "/Users/asuderma/repos/reactiveops/reckoner/reckoner/chart.py", line 232, in install
    raise e
HelmClientException: Command Failed with output below:
STDOUT:
STDERR: Error: failed to download "influx/influxdb" (hint: running `helm repo update` may help)

COMMAND: helm upgrade --install data influx/influxdb --namespace=tick --version=1.7.1

2019-01-08 08:40:57 root[36803]    ERROR ERROR: Some charts failed to install and were rolled back
2019-01-08 08:40:57 root[36803]    ERROR  - data
```

Snippet of course.yml
```
namespace: infra
repository: stable
minimum_versions:
  helm: 2.12.1
  reckoner: 0.10.1
repositories:
  incubator:
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
  influx:
    url: http://influx-charts.storage.googleapis.com
charts:
  data:
    namespace: tick
    chart: influxdb
    version: 1.7.1
    repository: influx
```
Reckoner v0.10.2
Helm v2.12.1

**Comment by sudermanjr** [comment]
This is an issue with the repository, not reckoner.
